### ISSUE TITLE
More visibility issues with text

### ISSUE THREAD

**Issue by ghost** [PEM--/meteor-helper#24]
See below. Is there something I need to set to fix this so it's more visible?

![meteorerr](https://cloud.githubusercontent.com/assets/440132/5989920/c1c46d5c-a94d-11e4-8905-38ab1f05387c.png)

**Comment by PEM--** [comment]
This plugin relies on the currently used theme. Atom gives you the capability to modify the theme that you've chosen in `~/.atom/styles.less`. You should be able to override the settings that your theme has set.

I personally use the default Dark them. Here's an example of its rendering:
![capture d ecran 2015-01-31 a 23 16 13](https://cloud.githubusercontent.com/assets/227831/5990047/be95e924-a99f-11e4-8aa2-d229e8d67aba.png)

**Comment by CaptSaltyJack** [comment]
My custom stylesheet looks like this:

    .tree-view {

    }

    atom-text-editor {

    }

    atom-text-editor .cursor {

    }

What classes do I need to change to set the colors in the Meteor pane?

**Comment by PEM--** [comment]
You can fire up the DevTools in Atom :wink: This gives you the exact classes that you want to modify thanks to the inspector. In your `~/.atom/styles.less`, you could add this:
```less
.meteor-helper .panel-body p {
 color: cornsilk;
}
```
