### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by aramix** [PEM--/meteor-helper#26]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:54:11)
MeteorHelperView._displayPane (/home/aram/.atom/packages/meteor-helper/lib/meteor-helper-view.coffee:112:9)
```

**Comment by PEM--** [comment]
Thanks for the pointer on the doc and the feedback. Should be OK now with 0.20.0.
