### ISSUE TITLE
keyboard shortcut to hide/show the terminal

### ISSUE THREAD

**Issue by sys13** [PEM--/meteor-helper#27]
Sometimes the terminal can take up a lot of the screen. Clicking on the Meteor Helper bar requires me to use the mouse which is a bit slow. It would be helpful if there was a keyboard shortcut (Ctrl + Alt + Something) to hide/show the terminal.

**Comment by PEM--** [comment]
I've killed the mouse :mouse: :gun:

Linux : Ctrl + Alt + S
Mac : Cmd + Alt + S

For showing / hiding Meteor's pane.
