### ISSUE TITLE
console font size option

### ISSUE THREAD

**Issue by robmoggach** [PEM--/meteor-helper#30]
ma français c'est un peux rouillé -
THANK YOU. love this package... and all the famous-views work you do...
Any chance of adding an option for changing your meteor console font & size?
doing dev away from a big screen on a 13" macbook it's difficult to read the output.

**Comment by PEM--** [comment]
You're welcome.

Atom allows you to overwrite its style in a specific file named `~/.atom/styles.less` (more info [here](https://atom.io/docs/v0.61.0/customizing-atom)). That could help you having a specific style when you are away from home with your MacBook.

For instance:
**~/.atom/styles.less**
```less
.meteor-helper .panel-body p {
  font-size: 14px;
}
```
