### ISSUE TITLE
Cannot find Settings for package (Win7, Atom v190)

### ISSUE THREAD

**Issue by batjko** [PEM--/meteor-helper#32]
Hi there,

I just installed this package and since it won't launch Meteor with the default settings (assumes *nix path by default), I wanted to go into the settings and change it.

However, there are no settings.
When I click on the Settings button for the package, I only get the README and nothing else:

![image](https://cloud.githubusercontent.com/assets/7287076/7042931/6e0d03ee-dddd-11e4-97cf-2174a35e8aa7.png)

![image](https://cloud.githubusercontent.com/assets/7287076/7042937/74491b44-dddd-11e4-9165-f40cf5078bc6.png)

**Comment by PEM--** [comment]
Wow, super weird. I will check this out. Thanks for the feedback.

**Comment by PEM--** [comment]
Should be fixed with 0.22.0.

**Comment by PEM--** [comment]
Dawn! It works in dev mode and not in production mode. I'm re-opening the issue.

**Comment by batjko** [comment]
No worries. Thanks for working on this.

**Comment by PEM--** [comment]
Pfew... Done in 0.23.0.

**Comment by voidale** [comment]
@PEM-- same problem here with latest 0.27 and latest atom win10 weird, how can we set custom settings with a file maybe?

**Comment by PEM--** [comment]
Yes, in Atom, all you settings are available in a `config.cson` file. 
![capture d ecran 2016-01-20 a 08 16 06](https://cloud.githubusercontent.com/assets/227831/12442190/1b651840-bf4e-11e5-98ea-be13db8cf938.png)

**Comment by voidale** [comment]
@PEM-- thanks can you share full settings file? because I'm not sure what should be over there as ou can see I don't have the settings tab or after clicking the package the only thing I see is README 
![capture](https://cloud.githubusercontent.com/assets/4450730/12442229/8e48f386-bf4e-11e5-9624-1c8aae8e19e6.PNG)

**Comment by PEM--** [comment]
Here are my current settings:
```coffee
  "meteor-helper":
    meteorAppPath: "app"
```
Sounds like Atom has changed something again. Try clicking on the grey pane, the settings shows up.
![settings](https://cloud.githubusercontent.com/assets/227831/12442680/49d6b784-bf52-11e5-9e89-eeb470e665dd.gif)

**Comment by voidale** [comment]
@PEM-- yeah i don't have the settings inside it's empty, just README is showed. I'm using latest atom version.

**Comment by PEM--** [comment]
Close your setting's pane and try to fire Meteor once using the helper (even if it fails owing to missing settings). This remember me an old Atom bugs where the settings weren't loaded until a package has used them.

**Comment by voidale** [comment]
@PEM-- yes you're right, I did meteor toggle and have the console stay open and open settings tab again and settings button appears :) Thanks a lot! I have tried this with from the FAQ, I guess you have also to close the settings tab + don't use the search look for the package manually.

**Comment by PEM--** [comment]
Weird behavior anyway. I hope Atom's team will fix that. Triggering a plugin just to show its settings is kind of messy knowing that the settings are serialized into the `config.cson` file already available at Atom's startup.

**Comment by s7dhansh** [comment]
I can't see the settings still! 0.27.0 - ubuntu 15.04 - atom 1.4.0

**Comment by s7dhansh** [comment]
A few restarts later, it does. Weird Atom.
