### ISSUE TITLE
Windows - Meteor command not found: /usr/local/bin/meteor

### ISSUE THREAD

**Issue by dtrimsd** [PEM--/meteor-helper#34]
I found your instructions in README.md.

In your step 3 you state: Create a launcher in the folder for your project. What do you mean? I've added a  launcher.cmd under my Meteor project directory, and various other places. No matter what I do I still get the original error message. 

Suggestions?

By the way, I could not install your package via the Atom gui. I had to use the command line as per https://zenagiwa.wordpress.com/2015/02/15/installing-packages-for-atom-on-windows/.

**Comment by PEM--** [comment]
Hi @dtrimsd. Actually, no suggestion at all... I don't own any Windows computer. The steps in the README have been gently provided by @tbiggins in #25.

If you find a better approach, please share it. Windows support for Meteor has just been added, I'm sure that it will benefit to other users.

**Comment by dtrimsd** [comment]
FWIW:

The Windows Meteor installer instals Meteor, node.js, and mongo/mongodb all under the following directory: C:\Users\Worker\AppData\Local\.meteor

Underneath that directory is a 'meteor.bat' file.

As part of the Meteor install this directory is added to the System Path environment variable.

Once that is done I can open up a Command Window and then navigate to any directory I want to start a Meteor project under. Once there I just enter: "meteor create projectname". Meteor creates the project. I then do a 'cd projectname' and then 'meteor' to start the application.

Also, to terminate meteor, mongo, node.js I just close the one command window.

Works every time.

I'm trying to use meteor-helper. I haven't been able to get it to work using other suggestions so i did a bit of poking around. I found that you set up your defaults in: C:\Users\worker\.atom\packages\meteor-helper\lib\meteor-helper.coffee

I made changes to:

 meteorPath:
      type: 'string'
      description: 'Customize Meteor\'s launching command'
      default: '/usr/local/bin/meteor'
      order: 2

Using this default I receive the following error: Meteor command not found: /usr/local/bin/meteor

Makes sense.

I then tried:

default: 'C:/Users/worker/AppData/Local/.meteor'
	-Arguments to path joint must be string.

default: 'C:/Users/worker/AppData/Local/.meteor/'
	-Arguments to path join must be string

default: 'C:/Users/worker/AppData/Local/.meteor/meteor'
	-Meteor command not found: C:/Users/worker/AppData/Local/.meteor/meteor

default: 'C:\Users\worker\AppData\Local\.meteor'
	-Meteor command not found: c:UsserworkerAppDataLocal.meteor

default: 'C:\\Users\\worker\\AppData\\Local\\.meteor'
	-Arguments to path join must be strings

default: 'C:\\Users\\worker\\AppData\\Local\\.meteor\\'
	-Arguments to path join must be strings

default: 'C:\\Users\\worker\\AppData\\Local\\.meteor\\meteor'
	Meteor command not found: c:\Users\worker\appData\local\.meteor\Meteor

I can't seem to come up with a happy default. I'm guessing part of the problem is that the directory path contains '...local\.meteor' I think that the '\.' might be an issue.

I haven't a clue why sometimes I'm told it's not a string and other times I am. Unfortunately when it's accepted it's a bad directory path. Any suggestions?

On a different issue. Would you consider altering your meteor-helper so that two command windows can be opened at the same time? 

With one command window you can start Meteor and watch the log. However, what do you do if you need to do a 'meteor mongo' command? For that to work one window must be running the application. A second window must be opened, then navigate to the directory the application is running in, then enter 'meteor mongo'. 

I've wanted a way to open up one command window, navigate to the application directory, then start up the application. If at some point I wanted to use mongo I'd like to have a function that would open up a second command window, automatically navigate to the application directory, then allow me to enter the 'meteor mongo' command with any options I might want to use.

**Comment by dtrimsd** [comment]
The Windows Meteor installer instals Meteor, node.js, and mongo/mongodb all under the following directory: C:\Users\Worker\AppData\Local\.meteor

I'd have sworn I'd added the \.meteor in my original message. Sorry.

**Comment by dtrimsd** [comment]
Aaaaaarrrrrg....

This editor changes my text. The directory is:

C;\Users\Worker\AppData\Local\<dot>meteor

Its is not \Local.meteor

**Comment by dtrimsd** [comment]
It changed it again. It should be:

C:\Users\worker\AppData\Local \ . meteor

Without the spaces.

**Comment by PEM--** [comment]
Poking around is the right way to go :+1: 

The file `C:\Users\worker.atom\packages\meteor-helper\lib\meteor-helper.coffee` is the default setting. Normally, this file is exposed in the settings of the plugin. If we found the appropriate value to setup, I will change it so that it holds the appropriate value for Windows.

In JS as well as in CS, the `\` is a special string character for inserting... special character. What Atom is telling you is to use its [`path` library](https://nodejs.org/api/path.html). You could use something like `path.join` to create the proper expected path on Windows.

Could you try something like `C:\\Users\\Worker\\AppData\\Local.meteor`?

**Comment by alican-k** [comment]
C:\\Users\\alican\\AppData\\Local\\.meteor\\meteor.bat
This path worked for me. So, it requires bat file to be added.

**Comment by JohnAReid** [comment]
Just spent the last three hours trying to get it to work with windows 8.1 (64 bit). In the end all I had to do was change the setting in the package so that the meteor path included the meteor.bat file as in alican-k message above.
It did not require a revised atommeteor,bat file or an launcher.cmd file.

**Comment by PEM--** [comment]
:+1:  @JohnAReid Could you create a PR out of it? That would certainly help some guys around.

**Comment by JohnAReid** [comment]
@PEM-- Sorry not sure what you mean by PR - however here is a screen shot of my settings which work:
![capture](https://cloud.githubusercontent.com/assets/7714810/7792925/a1483178-02b0-11e5-86d2-3dcf2d677e8f.PNG) 
Where john is the user name - I tried using the windows variable of %LOCALAPPDATA% which should substitute the C:\Users\john\AppData\Local bit and make it more generic but it did not work.

**Comment by PEM--** [comment]
Thank you for sharing. Indeed, very easy once you see the solution. I'm sure that will help a lot of Windows users. I think there's a way to create defaults depending on OS. Node has access the environment variables. Extrapolating `%LOCALAPPDATA%` and putting it as a default on the Windows's platform would be cleaner that just a documentation update. I will check this out.

PS : A PR is a **pul request** :wink:

**Comment by JohnAReid** [comment]
Thanks hope it will help others! - one suggestion I would make is to  have two  menu items "Launch Meteor"  and "Stop Meteor" and hide one depending on state of meteor running.

**Comment by PEM--** [comment]
I've found that toggling was faster when you need to relaunch Meteor, which starts to be very rare now since 0.8. Plus, it only takes one key combo.

**Comment by ankitappuria** [comment]
I have installed meteor  and I am getting this error while running meteor command from terminal `\AppData\Local\.meteor\packages\meteor-tool\1.1.1\mt-os.windows.x86_32\ was unex
pected at this time`

**Comment by PEM--** [comment]
Hi @ankitappuria, you should use the Meteor's forum for that. There should be some Windows users that could help you out there: https://forums.meteor.com

**Comment by thomasrivette** [comment]
On startup of meteor in simple-todos I receive and error after
=> Started Proxy
Unexpected mongo exit code 48. Restarting.
Unexpected mongo exit code 48. Restarting.
Unexpected mongo exit code 48. Restarting.
Can't start Mongo server.
MongoDB exited because  its port was closed, or was already take by a previous instance of MongoDB

Check for other processes listening on port 3001
or other Meteor instances running in the same project.

**Comment by nosizejosh** [comment]
this works!!! 
> C:\Users\your_username\AppData\Local\.meteor\meteor.bat

**Comment by ghost** [comment]
After uninstalling meteor , cannot install meteor via InstalMeteor.exe in win 8
