### ISSUE TITLE
Package.activateResources is deprecated.

### ISSUE THREAD

**Issue by bzavala** [PEM--/meteor-helper#37]
The context menu CSON format has changed. Please see
https://atom.io/docs/api/latest/ContextMenuManager

**Comment by PEM--** [comment]
Hi @bzavala, I don't see any changes out there. This is the current code for the context menu:
```coffee
'context-menu':
  'atom-workspace': [
    'label': 'Launch Meteor'
    'command': 'meteor-helper:toggle'
  ]
```
