### ISSUE TITLE
A suggestion - more than an issue

### ISSUE THREAD

**Issue by JohnAReid** [PEM--/meteor-helper#39]
I have been using meteor-helper for a free weeks now and overall it is just great - however I find it is slow in loading pages within the browser (up to three minutes before the local host page is completed) - so I bought a ssd to speed things up and to my surprise it did not make much noticeable difference. What is taking the time is for Meteor itself to run (using the Meteor command). 

If possible I would suggest that in the atom console display, meteor helper could show when the Meteor program is loaded.

**Comment by PEM--** [comment]
3 minutes for your page to load. Man, this is terrible. Even on massive app, I rarely wait more than 15s and I find it a pain (well more a warning for me to split my app).

For meteor-helper, I check what Meteor is writing on stdout and stderr. Depending on what is analyzed the icon on the right shows you the status. There's already a state that shows you when the build is finished (the green check icon). Hotcode push in your app should be fired within 2 to 3s.

**Comment by JohnAReid** [comment]
Yes it is a right pain, some of the times I get the green icon but mostly I get the spinning icon but the console reports the app is running and the browser local app is OK. 

I have tried the sample app  "meteor create simple-todos" and the response time is a lot faster so the delay could be caused by the angular meteor package - but even with the sample app I still get the spinning icon rather than the green icon.

**Comment by PEM--** [comment]
Basically, I track the status of the app using a simple regexp (https://github.com/PEM--/meteor-helper/blob/master/lib/meteor-helper-view.coffee#L328). Thus, depending on what the app is printing on stdout, the displayed state could be wrong.

If you log to syslog-ng, logstash, loggly and so forth, the displayed messages of Meteor stays verbatim making the state watcher OK again.

**Comment by JohnAReid** [comment]
@PEM-- Thanks
