### ISSUE TITLE
Use environment variables from .bash_profile

### ISSUE THREAD

**Issue by ianpogi5** [PEM--/meteor-helper#43]
I use .bash_profile to define environment variables like VELOCITY=0. 

How can I get this package to read it before launching meteor?

**Comment by PEM--** [comment]
This package uses Atom's `BufferedProcess` to launch Meteor: https://github.com/PEM--/meteor-helper/blob/master/lib/meteor-helper-view.coffee#L280

Thus, if your environment variables are available within Atom, they should be transmitted to Meteor.

**Comment by ianpogi5** [comment]
Ok I was able to resolve my problem by following this SO post: http://stackoverflow.com/questions/603785/environment-variables-in-mac-os-x

Thanks for pointing me to the right direction.

**Comment by PEM--** [comment]
Happy users make happy developers :smile:

**Comment by ianpogi5** [comment]
Very true!
