### ISSUE TITLE
No Meteor project found in:  atom:/config/.meteor

### ISSUE THREAD

**Issue by tvld** [PEM--/meteor-helper#46]
On Ubuntu 15.04 getting " No Meteor project found in:  atom:/config/.meteor", despite a lot of fiddling with many of the Path en App Path settings. Seems so obvious, what am I overlooking?

My app (and .meteor folder)  is in /home/tom/my-app

**Comment by tvld** [comment]
Found my own solution through trial and error:  Apparently Atom did not see my folder as a real Project Folder. For now I leave this one open, as the error-message really was clueless.

**Comment by PEM--** [comment]
Could be interesting that you add something in the FAQ at the end of the README and how you detect/fix it. Other users could stumble on this.

**Comment by shinank** [comment]
@tvld What was your solution? I am having the same issue with Atom 1.6 on OS X. TIA

**Comment by tvld** [comment]
Actually I dont have the exact details. However, what I recall is that you should add a Project in Atom. At first I was just using a folder and in Atom that is something different.

**Comment by shinank** [comment]
@tvld Thanks for the suggestion. Unfortunately, it didn't help me because I am already adding my folder as a Project.

**Comment by shinank** [comment]
I honestly didn't change anything. I was actually looking at the src for meteor-helper to start trying to figure out why my project wasn't being detected as a project and then I noticed that the icon for my project was different than before. And it detects meteor in my project just fine now. I didn't change anything but the issue just sorted itself out.
