### ISSUE TITLE
Ctrl-Alt-M duplicate

### ISSUE THREAD

**Issue by tvld** [PEM--/meteor-helper#47]
On Linux we have 

`ctrl-alt-m	bracket-matcher:select-inside-brackets	Bracket Matcher	.platform-linux atom-text-editor`

This does not play well with the same keybinding to Toggle Meteor...

**Comment by tvld** [comment]
Solved for now with adding:
```
'atom-workspace':
  'ctrl-cmd-m': 'meteor-helper:toggle'
  'ctrl-cmd-r': 'meteor-helper:reset'
  'ctrl-cmd-s': 'meteor-helper:showHide'
```

to the file keymap.cson

**Comment by PEM--** [comment]
Indeed, Atom lets you override the keymap settings. Feel free to add this in the documentation. Contributions are warmly welcomed :smile:
