### ISSUE TITLE
mongoOplogURL should be read from config

### ISSUE THREAD

**Issue by jazeee** [PEM--/meteor-helper#48]
Based on a bug I saw, I discovered that the code is not reading the Atom config for mongoOplogURL around line:
https://github.com/PEM--/meteor-helper/blob/master/lib/meteor-helper-view.coffee#L135

I will create a PR.

As a workaround, one can add a parameter into mup.json such as `"MONGO_OPLOG_URL": "mongodb://localhost:27017/..."`

**Comment by PEM--** [comment]
Hi @jazeee. Indeed, the setting was defined but not used properly. Thanks. Merging it and fixing another weird issue concerning the panel style.

**Comment by jazeee** [comment]
Excellent. Thanks!
