### ISSUE TITLE
Add option to disabled Meteor Up overrides.

### ISSUE THREAD

**Issue by natecox** [PEM--/meteor-helper#50]
I recently started deploying to production with Meteor Up, and discovered that meteor-helper reads the `mup.json` file to get and override port settings.

While I see the value for some, this is actually irritating to me. I view the `mup.json` as production values, that I may or may not want to have reflected on my local development machine. Essentially, I want my application running on port 3050 in production, but port 3000 for local development.

I think the simplest solution is to just add a toggle for respecting `mup.json` or not.

**Comment by PEM--** [comment]
Sounds like an easy one. I will check this out.
