### ISSUE TITLE
Not launching with atom from brew

### ISSUE THREAD

**Issue by elyase** [PEM--/meteor-helper#51]
New atom install using brew. When I Cmd-alt-M I get this:

![screenshot 2015-11-18 01 24 54](https://cloud.githubusercontent.com/assets/1175888/11229199/49452cf6-8d93-11e5-90c2-7ae0640d5647.png)

In the command line meteor runs ok. Any ideas?

**Comment by PEM--** [comment]
Never seen this one. According to my search on Google, it seems related to node-browserify or node-resolve: https://github.com/substack/node-browserify/issues/1111

You can disable the packages in Atom to check which one is causing the issue.

**Comment by elyase** [comment]
It is weird but it is working now, I just added a package to meteor and after rebuilding the problem went away.
