### ISSUE TITLE
I can't run Meteor on Windows 7 or 10

### ISSUE THREAD

**Issue by thomasrivette** [PEM--/meteor-helper#56]
After install i am able to run meteor creat fro the appdata/local/.meteor directory.  When I cd to simple-todo i see ".meteor, js, html,css" directory and files.  When I open a browser and type "http://localhost:3000"  i receive "This webpage is not available"...Please let me know if you are able to assist.

**Comment by PEM--** [comment]
Duplicate from #55 and not related to this plugin.

**Comment by PEM--** [comment]
I insist. If you can run Meteor, there's nothing that this plugin can do. You have to found out why you can't run `meteor` like any regular command. This plugin just does that.

**Comment by thomasrivette** [comment]
I apologize PEM, I was attempting to post on Meteor and responding to email directly.  Thank you for your help.
