### ISSUE TITLE
NODE_ENV shouldn't always be = production

### ISSUE THREAD

**Issue by productiveme** [PEM--/meteor-helper#58]
Hi there,

Love the package and use it everywhere. I sometimes do some checks against NODE_ENV in my code, but when running a meteor project on local with this package, it always reports NODE_ENV=production. Could you add a setting to override that?

**Comment by PEM--** [comment]
Thanks for the contrib. I've just published it.

By the way, don't forget to star the project if it pleases you 😉

**Comment by productiveme** [comment]
Nice, thanks!
